import os
import joblib
import numpy as np
import pandas as pd
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, root_mean_squared_error


PROCESSED_DATA_PATH = os.path.join("data", "processed", "daily_demand.csv")
MODEL_DIR = "models"


def create_time_features(df: pd.DataFrame) -> pd.DataFrame:
    """Generates lag features and calendar indicators for time-series forecasting."""
    df = df.copy()
    df["date"] = pd.to_datetime(df["date"])
    df = df.sort_values("date").reset_index(drop=True)

    # Calendar features
    df["day_of_week"] = df["date"].dt.dayofweek
    df["month"] = df["date"].dt.month
    df["day"] = df["date"].dt.day

    # Time-series lag features
    df["lag_1"] = df["total_units_sold"].shift(1)
    df["lag_7"] = df["total_units_sold"].shift(7)
    df["rolling_mean_7"] = df["total_units_sold"].shift(1).rolling(window=7).mean()

    # Drop missing values generated by lagging
    df = df.dropna().reset_index(drop=True)
    return df


def train_model() -> None:
    """Trains an XGBoost regressor and saves the model artifact."""
    if not os.path.exists(PROCESSED_DATA_PATH):
        raise FileNotFoundError("Processed dataset missing. Run 'python -m src.data_loader' first.")

    df = pd.read_csv(PROCESSED_DATA_PATH)
    featured_df = create_time_features(df)

    # Define features and target
    features = ["avg_price", "day_of_week", "month", "day", "lag_1", "lag_7", "rolling_mean_7"]
    target = "total_units_sold"

    X = featured_df[features]
    y = featured_df[target]

    # Time-series split (80% train, 20% test chronologically)
    split_idx = int(len(featured_df) * 0.8)
    X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
    y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]

    # Train XGBoost model
    model = XGBRegressor(n_estimators=100, learning_rate=0.05, max_depth=5, random_state=42)
    model.fit(X_train, y_train)

    # Evaluate predictions
    predictions = model.predict(X_test)
    mae = mean_absolute_error(y_test, predictions)
    rmse = root_mean_squared_error(y_test, predictions)

    print("--- Model Performance ---")
    print(f"MAE:  {mae:.2f}")
    print(f"RMSE: {rmse:.2f}")

    # Save model artifact
    os.makedirs(MODEL_DIR, exist_ok=True)
    model_path = os.path.join(MODEL_DIR, "demand_model.pkl")
    joblib.dump(model, model_path)
    print(f"Model saved successfully to {model_path}")


if __name__ == "__main__":
    train_model()